name: plsql-lab1
services:
  oracle-xe:
    image: gvenzl/oracle-xe:18-slim
    container_name: oracle-xe
    restart: unless-stopped

    ports:
      - "1521:1521"
      - "5500:5500"

    environment:
      ORACLE_PASSWORD: password
      ORACLE_DATABASE: lab1
      APP_USER: admin
      APP_USER_PASSWORD: password

    volumes:
      - oracle-data:/opt/oracle/oradata

volumes:
  oracle-data:
