CREATE SMALLFILE TABLESPACE "USER_DATA" 
		DATAFILE 'C:\oraclexe\app\oracle\oradata\XE\user_data.dbf' SIZE 5M 	
		AUTOEXTEND ON NEXT 2M MAXSIZE UNLIMITED 
		LOGGING 
		EXTENT MANAGEMENT LOCAL 
		SEGMENT SPACE MANAGEMENT AUTO; 

CREATE SMALLFILE TEMPORARY TABLESPACE "TEMP_DATA" 
		TEMPFILE 'C:\oraclexe\app\oracle\oradata\XE\temp1_data.dbf' SIZE 5M 
		AUTOEXTEND ON NEXT 2M MAXSIZE UNLIMITED 
		EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M;

-- DROP TABLESPACE TEMP_MAIN INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;